require 'seatbelt/models/hotel'
require 'seatbelt/models/flight'
require 'seatbelt/models/airport'
require 'seatbelt/models/offer'
require 'seatbelt/models/picture'
require 'seatbelt/models/travel_request'
require 'seatbelt/models/travel_response'
